name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main

jobs:
  jekyll-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site with Jekyll
        env:
          JEKYLL_ENV: production
          BUNDLE_WITH: 'jekyll_plugins'
        run: bundle exec jekyll build --trace

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_DEPLOY_TOKEN }}
          external_repository: lu494/lu494.github.io
          publish_branch: gh-pages
          publish_dir: ./_site
